spring:
  application:
    name: Order-Service
    
  profiles:
    active: kafka, local  
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
server:
  port: 9094
  
jwt:
  secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  
  

